image: denoland/deno:alpine-1.11.2

variables:
  # Set default neo4j password to "vertex"
  NEO4J_AUTH: neo4j/vertex
  # We need APOC functionality like triggers:
  NEO4JLABS_PLUGINS: '["apoc"]'
  NEO4J_apoc_trigger_enabled: "true"

test:
  stage: test
  services:
    - neo4j:4.2
  script:
    - deno run --allow-net --allow-write vertex/lib/test-setup.ts
    - deno test --allow-net --allow-read

lint:
  stage: test
  script:
    - deno lint
