# Configuration for a docker-compose environment to run tests for Vertex Framework
version: '3'
services:
  ################################################################
  # Neo4j graph database
  ################################################################
  neo4j:
    image: neo4j:4.3
    environment:
      # Set default password to "vertex"
      NEO4J_AUTH: neo4j/vertex
      # We need trigger functionality, which is part of "APOC" and must be enabled:
      NEO4JLABS_PLUGINS: '["apoc"]'
      NEO4J_apoc_trigger_enabled: "true"
      # The following is needed for apoc.export.cypher.all, even though we're only exporting to memory, not disk.
      apoc.export.file.enabled: "true"
    ports:
      - 7774:7474  # Browse on your host at http://localhost:7774/browser/?connectURL=neo4j://localhost:7777
      - 7777:7687  # Bolt

  # ################################################################
  # # Deno container for tests
  # ################################################################
  # tester:
  #   build:
  #     context: .
  #   depends_on:
  #     - neo4j
  #   stdin_open: true
  #   tty: true
  #   volumes:
  #     - .:/testenv/
