# Configuration for a docker-compose environment to run tests for Vertex Framework
version: '3'
services:
  ################################################################
  # Neo4j graph database
  ################################################################
  neo4j:
    image: neo4j:5.1.0
    environment:
      # Set default password to "vertex"
      NEO4J_AUTH: neo4j/vertex
      # We need trigger functionality, which is part of "APOC" and must be enabled:
      # The following will enable "APOC Full", but it takes time to download and install.
      # NEO4JLABS_PLUGINS: '["apoc"]'
      # We only need APOC core, which is included in the image; we only have to change the plugins directory to enable it:
      NEO4J_server_directories_plugins: /var/lib/neo4j/labs
      NEO4J_dbms_security_procedures_unrestricted: apoc.*
      # Enable trigger functionality:
      apoc.trigger.enabled: "true"
      # The following is needed for apoc.export.cypher.all, even though we're only exporting to memory, not disk.
      apoc.export.file.enabled: "true"
    ports:
      - 7774:7474  # Browse on your host at http://localhost:7774/browser/?connectURL=neo4j://localhost:7777
      - 7777:7687  # Bolt
