# Configuration for a docker-compose environment to run tests for Vertex Framework
version: '3'
services:
  ################################################################
  # Neo4j graph database
  ################################################################
  neo4j:
    image: neo4j:4.1
    environment:
      # Set default password to "vertex"
      NEO4J_AUTH: neo4j/vertex
      # Enable automatic UUID creation on nodes
      NEO4JLABS_PLUGINS: '["apoc"]'
      apoc.uuid.enabled: "true"
      apoc.trigger.enabled: "true"

  ################################################################
  # NodeJS container for tests
  ################################################################
  tester:
    build:
      context: .
    depends_on:
      - neo4j
    stdin_open: true
    tty: true
    volumes:
      - .:/testenv/
