# Configuration for a docker-compose environment to run tests for Vertex Framework
version: '3'
services:
  ################################################################
  # Neo4j graph database
  ################################################################
  neo4j:
    # For ARM support (until we are compatible with Neo4j 4.4), use
    # image: neo4j/neo4j-arm64-experimental:4.3.14-arm64
    image: neo4j:4.3
    environment:
      # Set default password to "vertex"
      NEO4J_AUTH: neo4j/vertex
      # We need trigger functionality, which is part of "APOC" and must be enabled:
      # The following will enable "APOC Full", but it takes time to download and install.
      # NEO4JLABS_PLUGINS: '["apoc"]'
      # We only need APOC core, which is included in the image; we only have to change the plugins directory to enable it:
      NEO4J_dbms_directories_plugins: /var/lib/neo4j/labs
      NEO4J_dbms_security_procedures_unrestricted: apoc.*
      # Enable trigger functionality:
      NEO4J_apoc_trigger_enabled: "true"
      # The following is needed for apoc.export.cypher.all, even though we're only exporting to memory, not disk.
      NEO4J_apoc_export_file_enabled: "true"
    ports:
      - 7774:7474  # Browse on your host at http://localhost:7774/browser/?connectURL=neo4j://localhost:7777
      - 7777:7687  # Bolt

  # ################################################################
  # # Deno container for tests
  # ################################################################
  # tester:
  #   build:
  #     context: .
  #   depends_on:
  #     - neo4j
  #   stdin_open: true
  #   tty: true
  #   volumes:
  #     - .:/testenv/
